### ISSUE TITLE
Notifier added to group not usable in user Signal

### ISSUE THREAD

**Issue by markholster** [jecstarinnovations/etm#10]
The notifier added to a group is not usable for a user that is in that group. When the user adds a Signal in his user context he/she is able to select the notifier that's configured at the group level.

During signallin an error is logged:
Signal 'Test signa' of user '<username>' has a notifier '<notifier name>' configured but that user is not authorized for this notifier.

**Comment by jecstarinnovations** [comment]
Group data not in user context of Signal.
