### ISSUE TITLE
Enhance search screen with custom fields

### ISSUE THREAD

**Issue by markholster** [jecstarinnovations/etm#11]
Allow a user to configure his/her own search screen. It takes, for example, a lot of effort to select the events of a certain application. It would be convenient for users to be able to add event attributes as input/select box on the search screen.

**Comment by jecstarinnovations** [comment]
Tasks to do:

- [X] Rewrite search card
- [X] Prefill selects of additional query params.
- [ ] Narrow down prefilled query params based on relations.
- [ ] Import query should test if given field(s) are additional query params. If not add to query field.
- [ ] Export queries should add additional query params.
- [ ] Merge search-templates.js, searchresults.js and inline js into search.js
- [ ] SearchService should be able to handle new query layout.
- [ ] Update documentation
