### ISSUE TITLE
Unexplainable error: Found a cycle in the event order

### ISSUE THREAD

**Issue by markholster** [jecstarinnovations/etm#18]
Error executing query: Found a cycle in the event order. It is impossible to display the endpoints overview. (100000)

All data seems to be correctly correlated. The error occurs when multiple unconnected requests and responses  are nested within a top level event.

**Comment by jecstarinnovations** [comment]
This error is caused when the last event in the transaction is added to the DirectedGraph before the second single last backend request. We need to make the code independent of the order the transactional events are loaded from the database.
